baseURL: 'https://security.kaldei.xyz/'
canonifyURLs: true
languageCode: en-us
title: KDCN
theme: PaperMod
paginate: 15

markup:
  goldmark:
    renderer:
      unsafe: true
    extensions:
      typographer: false

params:
  title: KDCN
  defaultTheme: auto # Color theme (auto, light or dark)
  disableScrollToTop: true # Disable scroll to top button
  mainSections: [] # Don't display posts list on Home Page
  ShowCodeCopyButtons: true # Enable button in code block
  assets:
    favicon: images/favicon.png


# Required for search bar
outputs:
    home:
        - HTML
        - RSS
        - JSON

menu:
  main:
    - name: Home
      identifier: home
      weight: 1
      url: /
    - name: Kill Chain
      weight: 2
      identifier: posts
      url: /killchain/
    - name: Tools
      weight: 3
      identifier: tools
      url: /tools/
    - name: WSTG Mind Map
      weight: 4
      identifier: WSTG Mind Map
      url: /wstgmap/
    - name: Search
      weight: 5
      identifier: search
      url: /search/
    - name: About
      weight: 6
      identifier: about
      url: /about/
